
# PROMPT section
export PS1="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;35m\]\u@\h\[\033[00m\]\[\033[01;34m\] ➜ \W\[\033[00m\]\$ "

alias launchEmulator="nohup emulator -avd Pixel_3a_API_29 &"
alias compress="zip MaderasRAMGO.zip -r * .[^.]* -x '*.git*' -x '*node_modules*'"
alias aws_sandbox="ssh -i /Users/<USER>/.ssh/id_rsa ec2-user@XXXXXXXXXZZZZZ.compute.amazonaws.com"

